### ISSUE TITLE
Discussion about method of self-attention.

### ISSUE THREAD

**Issue by xiejiachen** [thu-coai/CDial-GPT#17]
Actually, I am a fresher on NLP topics, and recently I am studying self-attention-schema referred from http://jalammar.github.io/illustrated-gpt2/#part-3-beyond-language-modeling .

And also from the related paper, such as http://papers.nips.cc/paper/7181-attention-is-all-you-need.pdf
and https://arxiv.org/abs/2006.16362 .

The core idea of attention is given the more related Key and Query with higher probability scores by
 
softmax(QK^T),  where higher product results implies higher correlation. And they made 2 fully - connected W_k and W_q to optimize.

I am confused about, **is that true: higher correlation = higher product results of QK ?** 

In my opinion, a more clearly approach way is directly use distance to express how pair of Q and K.

such as 

1.  softmax(-abs(Q-K)),  giving narrower distance of key and query higher probability
2.  softmax(-min(Q/K,K/Q)), similarly with above one, but use  division other than minus.

May these ideas works?--I mean might it conduct some useful research papers.

**Comment by silverriver** [comment]
There are vaious methods to obtain the attention score, e.g., 

1. Use dot product as in Transformer
2. Use a FeedForward layer (see "Neural Machine Translation by Jointly Learning to Align and Translate")
3. Use a bilinear layer (see "Effective Approaches to Attention-based Neural Machine Translation")

However, it turns out that (the experiment result indicates that), using dot product is a very effective and computational-cheap way to obtain the attention scores. Maybe the method proposed by you can produce better performance. But I suspect the performance improvement will be marginal.
